<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Carbon\Carbon;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $datetime = Carbon::today()->format('Y-m-d H:i:s');

        DB::table('users')->insert([
            [
                'office_id' => 1,
                'name' => 'スタッフ1',
                'kana' => 'すたっふいち',
                'email' => 'staff1@test.com',
                'password' => Hash::make('password'),
                'role' => 1,
                'can_manage_job_postings' => true,
                'can_manage_groupings' => true,
                'created_at' => $datetime,
                'updated_at' => $datetime,
            ],
            [
                'office_id' => 1,
                'name' => 'スタッフ2',
                'kana' => 'すたっふに',
                'email' => 'staff2@test.com',
                'password' => Hash::make('password'),
                'role' => 1,
                'can_manage_job_postings' => true,
                'can_manage_groupings' => true,
                'created_at' => $datetime,
                'updated_at' => $datetime,
            ],
            [
                'office_id' => 1,
                'name' => 'スタッフ3',
                'kana' => 'すたっふさん',
                'email' => 'staff3@test.com',
                'password' => Hash::make('password'),
                'role' => 1,
                'can_manage_job_postings' => true,
                'can_manage_groupings' => true,
                'created_at' => $datetime,
                'updated_at' => $datetime,
            ],
            [
                'office_id' => 1,
                'name' => 'スタッフ4',
                'kana' => 'すたっふよん',
                'email' => 'staff4@test.com',
                'password' => Hash::make('password'),
                'role' => 1,
                'can_manage_job_postings' => true,
                'can_manage_groupings' => true,
                'created_at' => $datetime,
                'updated_at' => $datetime,
            ],
            [
                'office_id' => 1,
                'name' => 'スタッフ5',
                'kana' => 'すたっふご',
                'email' => 'staff5@test.com',
                'password' => Hash::make('password'),
                'role' => 1,
                'can_manage_job_postings' => true,
                'can_manage_groupings' => true,
                'created_at' => $datetime,
                'updated_at' => $datetime,
            ],
            [
                'office_id' => 1,
                'name' => 'スタッフ6',
                'kana' => 'すたっふろく',
                'email' => 'staff6@test.com',
                'password' => Hash::make('password'),
                'role' => 1,
                'can_manage_job_postings' => true,
                'can_manage_groupings' => true,
                'created_at' => $datetime,
                'updated_at' => $datetime,
            ],
            [
                'office_id' => 1,
                'name' => 'スタッフ7',
                'kana' => 'すたっふなな',
                'email' => 'staff7@test.com',
                'password' => Hash::make('password'),
                'role' => 1,
                'can_manage_job_postings' => true,
                'can_manage_groupings' => true,
                'created_at' => $datetime,
                'updated_at' => $datetime,
            ],
            [
                'office_id' => 1,
                'name' => 'スタッフ8',
                'kana' => 'すたっふはち',
                'email' => 'staff8@test.com',
                'password' => Hash::make('password'),
                'role' => 1,
                'can_manage_job_postings' => true,
                'can_manage_groupings' => true,
                'created_at' => $datetime,
                'updated_at' => $datetime,
            ],
            [
                'office_id' => 1,
                'name' => 'スタッフ9',
                'kana' => 'すたっふきゅう',
                'email' => 'staff9@test.com',
                'password' => Hash::make('password'),
                'role' => 1,
                'can_manage_job_postings' => true,
                'can_manage_groupings' => true,
                'created_at' => $datetime,
                'updated_at' => $datetime,
            ],
            [
                'office_id' => 1,
                'name' => 'スタッフ10',
                'kana' => 'すたっふじゅう',
                'email' => 'staff10@test.com',
                'password' => Hash::make('password'),
                'role' => 1,
                'can_manage_job_postings' => true,
                'can_manage_groupings' => true,
                'created_at' => $datetime,
                'updated_at' => $datetime,
            ],
            [
                'office_id' => 1,
                'name' => 'スタッフ11',
                'kana' => 'すたっふじゅういち',
                'email' => 'staff11@test.com',
                'password' => Hash::make('password'),
                'role' => 1,
                'can_manage_job_postings' => true,
                'can_manage_groupings' => true,
                'created_at' => $datetime,
                'updated_at' => $datetime,
            ],
            [
                'office_id' => 1,
                'name' => 'スタッフ12',
                'kana' => 'すたっふじゅうに',
                'email' => 'staff12@test.com',
                'password' => Hash::make('password'),
                'role' => 1,
                'can_manage_job_postings' => true,
                'can_manage_groupings' => true,
                'created_at' => $datetime,
                'updated_at' => $datetime,
            ],
            [
                'office_id' => 1,
                'name' => 'スタッフ13',
                'kana' => 'すたっふじゅうさん',
                'email' => 'staff13@test.com',
                'password' => Hash::make('password'),
                'role' => 1,
                'can_manage_job_postings' => true,
                'can_manage_groupings' => true,
                'created_at' => $datetime,
                'updated_at' => $datetime,
            ],
            [
                'office_id' => 1,
                'name' => 'スタッフ14',
                'kana' => 'すたっふじゅうよん',
                'email' => 'staff14@test.com',
                'password' => Hash::make('password'),
                'role' => 1,
                'can_manage_job_postings' => true,
                'can_manage_groupings' => true,
                'created_at' => $datetime,
                'updated_at' => $datetime,
            ],
            [
                'office_id' => 1,
                'name' => 'スタッフ15',
                'kana' => 'すたっふじゅうご',
                'email' => 'staff15@test.com',
                'password' => Hash::make('password'),
                'role' => 1,
                'can_manage_job_postings' => true,
                'can_manage_groupings' => true,
                'created_at' => $datetime,
                'updated_at' => $datetime,
            ],
            [
                'office_id' => 2,
                'name' => 'スタッフ16',
                'kana' => 'すたっふじゅうろく',
                'email' => 'staff16@test.com',
                'password' => Hash::make('password'),
                'role' => 1,
                'can_manage_job_postings' => true,
                'can_manage_groupings' => true,
                'created_at' => $datetime,
                'updated_at' => $datetime,
            ],
            [
                'office_id' => 2,
                'name' => 'スタッフ17',
                'kana' => 'すたっふじゅうなな',
                'email' => 'staff17@test.com',
                'password' => Hash::make('password'),
                'role' => 1,
                'can_manage_job_postings' => true,
                'can_manage_groupings' => true,
                'created_at' => $datetime,
                'updated_at' => $datetime,
            ],
            [
                'office_id' => 2,
                'name' => 'スタッフ18',
                'kana' => 'すたっふじゅうはち',
                'email' => 'staff18@test.com',
                'password' => Hash::make('password'),
                'role' => 1,
                'can_manage_job_postings' => true,
                'can_manage_groupings' => true,
                'created_at' => $datetime,
                'updated_at' => $datetime,
            ],
            [
                'office_id' => 2,
                'name' => 'スタッフ19',
                'kana' => 'すたっふじゅうきゅう',
                'email' => 'staff19@test.com',
                'password' => Hash::make('password'),
                'role' => 1,
                'can_manage_job_postings' => true,
                'can_manage_groupings' => true,
                'created_at' => $datetime,
                'updated_at' => $datetime,
            ],
            [
                'office_id' => 3,
                'name' => 'スタッフ20',
                'kana' => 'すたっふにじゅう',
                'email' => 'staff20@test.com',
                'password' => Hash::make('password'),
                'role' => 1,
                'can_manage_job_postings' => true,
                'can_manage_groupings' => true,
                'created_at' => $datetime,
                'updated_at' => $datetime,
            ],
            [
                'office_id' => null,
                'name' => 'スタッフ21',
                'kana' => 'すたっふにじゅういち',
                'email' => 'staff21@test.com',
                'password' => Hash::make('password'),
                'role' => 1,
                'can_manage_job_postings' => true,
                'can_manage_groupings' => true,
                'created_at' => $datetime,
                'updated_at' => $datetime,
            ],
            [
                'office_id' => 1,
                'name' => 'メンバー1',
                'kana' => 'めんばーいち',
                'email' => 'member1@test.com',
                'password' => Hash::make('password'),
                'role' => 9,
                'can_manage_job_postings' => false,
                'can_manage_groupings' => false,
                'created_at' => $datetime,
                'updated_at' => $datetime,
            ],
            [
                'office_id' => 1,
                'name' => 'メンバー2',
                'kana' => 'めんばーに',
                'email' => 'member2@test.com',
                'password' => Hash::make('password'),
                'role' => 9,
                'can_manage_job_postings' => false,
                'can_manage_groupings' => false,
                'created_at' => $datetime,
                'updated_at' => $datetime,
            ],
            [
                'office_id' => 1,
                'name' => 'メンバー3',
                'kana' => 'めんばーさん',
                'email' => 'member3@test.com',
                'password' => Hash::make('password'),
                'role' => 9,
                'can_manage_job_postings' => false,
                'can_manage_groupings' => false,
                'created_at' => $datetime,
                'updated_at' => $datetime,
            ],
            [
                'office_id' => 1,
                'name' => 'メンバー4',
                'kana' => 'めんばーよん',
                'email' => 'member4@test.com',
                'password' => Hash::make('password'),
                'role' => 9,
                'can_manage_job_postings' => false,
                'can_manage_groupings' => false,
                'created_at' => $datetime,
                'updated_at' => $datetime,
            ],
            [
                'office_id' => 1,
                'name' => 'メンバー5',
                'kana' => 'めんばーご',
                'email' => 'member5@test.com',
                'password' => Hash::make('password'),
                'role' => 9,
                'can_manage_job_postings' => false,
                'can_manage_groupings' => false,
                'created_at' => $datetime,
                'updated_at' => $datetime,
            ],
            [
                'office_id' => 1,
                'name' => 'メンバー6',
                'kana' => 'めんばーろく',
                'email' => 'member6@test.com',
                'password' => Hash::make('password'),
                'role' => 9,
                'can_manage_job_postings' => false,
                'can_manage_groupings' => false,
                'created_at' => $datetime,
                'updated_at' => $datetime,
            ],
            [
                'office_id' => 1,
                'name' => 'メンバー7',
                'kana' => 'めんばーなな',
                'email' => 'member7@test.com',
                'password' => Hash::make('password'),
                'role' => 9,
                'can_manage_job_postings' => false,
                'can_manage_groupings' => false,
                'created_at' => $datetime,
                'updated_at' => $datetime,
            ],
            [
                'office_id' => 1,
                'name' => 'メンバー8',
                'kana' => 'めんばーはち',
                'email' => 'member8@test.com',
                'password' => Hash::make('password'),
                'role' => 9,
                'can_manage_job_postings' => false,
                'can_manage_groupings' => false,
                'created_at' => $datetime,
                'updated_at' => $datetime,
            ],
            [
                'office_id' => 1,
                'name' => 'メンバー9',
                'kana' => 'めんばーきゅう',
                'email' => 'member9@test.com',
                'password' => Hash::make('password'),
                'role' => 9,
                'can_manage_job_postings' => false,
                'can_manage_groupings' => false,
                'created_at' => $datetime,
                'updated_at' => $datetime,
            ],
            [
                'office_id' => 1,
                'name' => 'メンバー10',
                'kana' => 'めんばーじゅう',
                'email' => 'member10@test.com',
                'password' => Hash::make('password'),
                'role' => 9,
                'can_manage_job_postings' => false,
                'can_manage_groupings' => false,
                'created_at' => $datetime,
                'updated_at' => $datetime,
            ],
            [
                'office_id' => 1,
                'name' => 'メンバー11',
                'kana' => 'めんばーじゅういち',
                'email' => 'member11@test.com',
                'password' => Hash::make('password'),
                'role' => 9,
                'can_manage_job_postings' => false,
                'can_manage_groupings' => false,
                'created_at' => $datetime,
                'updated_at' => $datetime,
            ],
            [
                'office_id' => 1,
                'name' => 'メンバー12',
                'kana' => 'めんばーじゅうに',
                'email' => 'member12@test.com',
                'password' => Hash::make('password'),
                'role' => 9,
                'can_manage_job_postings' => false,
                'can_manage_groupings' => false,
                'created_at' => $datetime,
                'updated_at' => $datetime,
            ],
            [
                'office_id' => 1,
                'name' => 'メンバー13',
                'kana' => 'めんばーじゅうさん',
                'email' => 'member13@test.com',
                'password' => Hash::make('password'),
                'role' => 9,
                'can_manage_job_postings' => false,
                'can_manage_groupings' => false,
                'created_at' => $datetime,
                'updated_at' => $datetime,
            ],
            [
                'office_id' => 1,
                'name' => 'メンバー14',
                'kana' => 'めんばーじゅうよん',
                'email' => 'member14@test.com',
                'password' => Hash::make('password'),
                'role' => 9,
                'can_manage_job_postings' => false,
                'can_manage_groupings' => false,
                'created_at' => $datetime,
                'updated_at' => $datetime,
            ],
            [
                'office_id' => 1,
                'name' => 'メンバー15',
                'kana' => 'めんばーじゅうご',
                'email' => 'member15@test.com',
                'password' => Hash::make('password'),
                'role' => 9,
                'can_manage_job_postings' => false,
                'can_manage_groupings' => false,
                'created_at' => $datetime,
                'updated_at' => $datetime,
            ],
            [
                'office_id' => 2,
                'name' => 'メンバー16',
                'kana' => 'めんばーじゅうろく',
                'email' => 'member16@test.com',
                'password' => Hash::make('password'),
                'role' => 9,
                'can_manage_job_postings' => false,
                'can_manage_groupings' => false,
                'created_at' => $datetime,
                'updated_at' => $datetime,
            ],
            [
                'office_id' => 2,
                'name' => 'メンバー17',
                'kana' => 'めんばーじゅうなな',
                'email' => 'member17@test.com',
                'password' => Hash::make('password'),
                'role' => 9,
                'can_manage_job_postings' => false,
                'can_manage_groupings' => false,
                'created_at' => $datetime,
                'updated_at' => $datetime,
            ],
            [
                'office_id' => 2,
                'name' => 'メンバー18',
                'kana' => 'めんばーじゅうはち',
                'email' => 'member18@test.com',
                'password' => Hash::make('password'),
                'role' => 9,
                'can_manage_job_postings' => false,
                'can_manage_groupings' => false,
                'created_at' => $datetime,
                'updated_at' => $datetime,
            ],
            [
                'office_id' => 2,
                'name' => 'メンバー19',
                'kana' => 'めんばーじゅうきゅう',
                'email' => 'member19@test.com',
                'password' => Hash::make('password'),
                'role' => 9,
                'can_manage_job_postings' => false,
                'can_manage_groupings' => false,
                'created_at' => $datetime,
                'updated_at' => $datetime,
            ],
            [
                'office_id' => 3,
                'name' => 'メンバー20',
                'kana' => 'めんばーにじゅう',
                'email' => 'member20@test.com',
                'password' => Hash::make('password'),
                'role' => 9,
                'can_manage_job_postings' => false,
                'can_manage_groupings' => false,
                'created_at' => $datetime,
                'updated_at' => $datetime,
            ],
            [
                'office_id' => null,
                'name' => 'メンバー21',
                'kana' => 'めんばーにじゅういち',
                'email' => 'member21@test.com',
                'password' => Hash::make('password'),
                'role' => 9,
                'can_manage_job_postings' => false,
                'can_manage_groupings' => false,
                'created_at' => $datetime,
                'updated_at' => $datetime,
            ],
        ]);
    }
}
